### ISSUE TITLE
Bad quality image on french N64 system

### ISSUE THREAD

**Issue by JW-Akademia** [kbeckmann/PicoDVI-N64#6]
Hello, Thank you for this wonderful project. I built such an interface but after connecting to the TV I find that the image is of poor quality. The image is sharp but resolution is really low (the text is almost illegible) and the image shakes sometimes. What could it be caused by? (it's a NUS-001(EUR) N64 system)
![image](https://github.com/kbeckmann/PicoDVI-N64/assets/123083705/1e5fb78f-f51d-4c21-a4ba-5fafedcff226)
![image](https://github.com/kbeckmann/PicoDVI-N64/assets/123083705/3b8f831b-99c1-48a3-96ca-95cb94582a87)
![image](https://github.com/kbeckmann/PicoDVI-N64/assets/123083705/8ce29b2b-18cf-472a-ac0e-f54acbd6f9a8)
![image](https://github.com/kbeckmann/PicoDVI-N64/assets/123083705/04830af1-b134-406d-bf07-8d4f4496c6e3)
![image](https://github.com/kbeckmann/PicoDVI-N64/assets/123083705/51b28e19-1445-409c-b61d-22b28cc87cfa)

**Comment by papiamazing** [comment]
thanks for what you do, it's very nice, I wanted to understand why I too have the same problem, the image is a little better than the composite signal, but it is of low quality, on a 22 inch LCD it looks very grainy, if anyone has had the same problem it would be nice if you could share the solution, thanks again for all the projects you make available.

**Comment by spinalcode** [comment]
The video output is only 640x480. Some TV's look terrible when viewing such a low resolution, Samsung in particular. Do you get the same problem when viewing on a computer monitor?

The low resolution text is simply because the pico does not have enough memory for 640x480 video, so every second pixel is missed. However on your multicart menu, you can set the text size to large, this will look a little better.

**Comment by kbeckmann** [comment]
The image quality you are seeing is expected because of how this works.

PicoDVI-N64 works with a 320x240 internal framebuffer with rgb555 color depth.

The N64 can output up to 640x480 with rgb777.

The video signal is sampled every second pixel horizontally, and every second row is skipped. It's nearest-neighbor downscaling with other words.

If you see banding, this is because the color depth is rgb555. The N64 has rgb777. This is simply how it is implemented.
